# Generated by Django 5.0.6 on 2024-06-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofiles',
            managers=[
            ],
        ),
    ]
